<?php
// Again, we display a title as before and then we render the form.
// Zend Framework provides some view helpers to make this a little easier.
// The form() view helper has an openTag() and closeTag() method which we use
// to open and close the form. Then for each element with a label, we can use
// formRow(), but for the two elements that are standalone, we use formHidden()
// and formSubmit().

$title = 'Add new album';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
// These variables are passed from AlbumController->addAction()
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('title'));
// echo $this->formRow($form->get('artist'));
// echo $this->formSubmit($form->get('submit'));

// The process of rendering the form can be simplified by using the bundled
// formCollection view helper. This will iterate over the form structure,
// calling the appropriate label, element and error view helpers for each element
echo $this->formCollection($form);
echo $this->form()->closeTag();
